### ISSUE TITLE
[Bug] Cannot delete more than 200 gifs per run

### ISSUE THREAD

**Issue by JoshuaVandaele** [HeySreelal/Saved-GIFs-Remover#2]
The program currently cannot delete more than 200 saved GIFs per run, necessitating the tool to be ran multiple times.

**Comment by The0xArchitect** [comment]
Interesting. I actually didn't have any clue about it.

This happens most probably because the [messags.getSavedGifs](https://core.telegram.org/method/messages.getSavedGifs) returns only 200 per request.  I'll update this behavior soon, such that the script loops until the saved gifs list is empty.

Thanks for raising this.

**Comment by The0xArchitect** [comment]
Just fixed it, hope this will be helpful in the future :) 

Thanks again for reporting!
